In [128]:
#Load libraries
import pandas as pd
import numpy as np
from sklearn import model_selection
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier, export_graphviz


In [129]:
#Load dataset
url = "https://raw.githubusercontent.com/callxpert/datasets/master/Loan-applicant-details.csv"
names = ['Loan_ID','Gender','Married','Dependents','Education','Self_Employed','ApplicantIncome','CoapplicantIncome','LoanAmount','Loan_Amount_Term','Credit_History','Property_Area','Loan_Status']
dataset = pd.read_csv(url, names=names)

In [130]:
dataset.shape

(480, 13)

In [131]:
dataset['Loan_Status'].value_counts()

Y    332
N    148
Name: Loan_Status, dtype: int64

In [132]:
dataset.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001003   Male     Yes          1      Graduate            No   
1  LP001005   Male     Yes          0      Graduate           Yes   
2  LP001006   Male     Yes          0  Not Graduate            No   
3  LP001008   Male      No          0      Graduate            No   
4  LP001011   Male     Yes          2      Graduate           Yes   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             4583             1508.0         128               360   
1             3000                0.0          66               360   
2             2583             2358.0         120               360   
3             6000                0.0         141               360   
4             5417             4196.0         267               360   

   Credit_History Property_Area Loan_Status  
0               1         Rural           N  
1               1         Urban           Y  
2               1         Urban           Y  
3               1         Urban           Y  
4               1         Urban           Y

# Convert Categorical features to numerical values

In [133]:
from sklearn.preprocessing import LabelEncoder
var_mod = ['Gender','Married','Dependents','Education','Self_Employed','Property_Area','Loan_Status']
le = LabelEncoder()
for i in var_mod:
    dataset[i] = le.fit_transform(dataset[i])

In [134]:
dataset.head()

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
0  LP001003       1        1           1          0              0   
1  LP001005       1        1           0          0              1   
2  LP001006       1        1           0          1              0   
3  LP001008       1        0           0          0              0   
4  LP001011       1        1           2          0              1   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             4583             1508.0         128               360   
1             3000                0.0          66               360   
2             2583             2358.0         120               360   
3             6000                0.0         141               360   
4             5417             4196.0         267               360   

   Credit_History  Property_Area  Loan_Status  
0               1              0            0  
1               1              2            1  
2               1              2            1  
3               1              2            1  
4               1              2            1

In [135]:
from sklearn.model_selection import train_test_split

In [136]:
array = dataset.values
X = array[:,6:11]         
Y = array[:,12]
X = X.astype('int')
Y = Y.astype('int')
x_train, x_test, y_train, y_test = model_selection.train_test_split(X, Y, test_size=0.2, random_state=7)

In [137]:
print("Train set:", x_train.shape, y_train.shape)
print("Test set:", x_test.shape, y_test.shape)

Train set: (384, 5) (384,)
Test set: (96, 5) (96,)


# decision tree

In [138]:
model = DecisionTreeClassifier(criterion='entropy',max_depth=6)
model.fit(x_train,y_train)
predictions1 = model.predict(x_test)

In [139]:
predictions1

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1])

In [140]:
# evaluation of accuracy

In [141]:
from sklearn.metrics import accuracy_score,f1_score,log_loss
accuracy_score(y_test,predictions1)
#log_loss(y_test,predictions1)

0.7708333333333334

In [142]:
f1_score(y_test,predictions1)

0.8428571428571427

# logistic regression

In [143]:
model= LogisticRegression(C=0.01,solver='liblinear')
model.fit(x_train,y_train)
predictions2=model.predict(x_test)

In [144]:
predictions2

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

In [145]:
#jaccard
accuracy_score(y_test,predictions2)

0.6145833333333334

In [146]:
#f1_score
f1_score(y_test,predictions2)

0.7612903225806451

# k-nearest-neighbors

In [147]:
k=9
model=KNeighborsClassifier(n_neighbors=k)
model.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=9, p=2,
           weights='uniform')

In [148]:
#jaccard_index
predictions3 = model.predict(x_test)
print(accuracy_score(y_test, predictions3))

0.6354166666666666


In [149]:
predictions3

array([0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0])

In [150]:
#f1_score
f1_score(y_test,predictions3)

0.7586206896551725

# support vector machines

In [151]:
from sklearn import svm
model=svm.SVC(kernel='rbf')
model.fit(x_train, y_train)
#model=SVC()
#model.fit(x_train,y_train)

/opt/conda/envs/Python36/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [152]:
#jaccard_index
predictions4 = model.predict(x_test)
print(accuracy_score(y_test,predictions4))

0.6354166666666666


In [153]:
predictions4[0:5]

array([1, 1, 1, 1, 1])

In [154]:
#f1_score
f1_score(y_test,predictions4)

0.7770700636942676

In [155]:
from sklearn.metrics import accuracy_score

In [156]:
data = {'Algorithm':['decision trees', 'logestic_regression', 'KNN', 'SVM'], 
        'Jaccard':[accuracy_score(y_test, predictions1),accuracy_score(y_test, predictions2),accuracy_score(y_test, predictions3),accuracy_score(y_test, predictions4)],
        'F1-score':[f1_score(y_test,predictions1), f1_score(y_test,predictions2), f1_score(y_test,predictions3), f1_score(y_test,predictions4)],
        'LogLoss':['NA', 'NA', 'NA','NA']}
Final_output = pd.DataFrame(data)
Final_output.set_index('Algorithm')
Final_output

Algorithm   Jaccard  F1-score LogLoss
0       decision trees  0.770833  0.842857      NA
1  logestic_regression  0.614583  0.761290      NA
2                  KNN  0.635417  0.758621      NA
3                  SVM  0.635417  0.777070      NA